# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7de6fa0d5edb402f590a6589da0db114a6460f19fb26aa912e8dedbc037b4af962578f65ed3efa5504761163d049478ec53d3301faf28f7c406060b8bbd5c16a

test:
  secret_key_base: e99c841f9967ced28147fd8e7c8061a8323dc6c50ae7f635e4a7ea9bbc958f5b0c6a0993aebee507008d8a2af5841e372de9cb2984086320896c7f7c9eaee6bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
